### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by Janasek** [SilentButeo2/webgrabplus-siteinipack#461]
!! -- WARNING : programtv.interia.pl.E doesn't allow epg grabbing !!
it is advised to disable this channel / site from your channel list

I tried programtv.interia.pl.E.channels
and I have such a mistake
in addition, it appears in the programtv.interia.pl file

site {url=**programtv.onet.pl**|timezone=Europe/Warsaw|maxdays=13|cultureinfo=pl-PL|charset=UTF-8|titlematchfactor=90|episodesystem=onscreen}

should there be addresses from interia?

**Comment by Pancronos** [comment]
is a warning as explained here http://webgrabplus.com/faq 

What means "!! -- Warning :site doesn't allow EPG grabbing !!"?
This is an indication that the robots.txt indicates, it doesn't want automitic software to download part from a site.
Because WG++ conforms the ROBOTS exclusion standard, this warning is shown.
If that happens, you should check the website (that gives this warning) terms of usage. And if it doesn't allow you to grab automatic from the site (or parts from it), you should disable this website in your config file (or a part of it).
So this warning doesn't mean that WG++ can't grab the EPG data. It just means, the website doesn't want you to grab the EPG data.
