### ISSUE TITLE
movistarplus.es not working as registered_user

### ISSUE THREAD

**Issue by flosoft** [SilentButeo2/webgrabplus-siteinipack#565]
movistarplus.es does not work update when logged in as a `registered_user`.
It works just fine when not logged in.

When logged in, it gets stuck at the following stage:
```
(   2/11  ) MOVISTARPLUS.ES -- chan. (xmltv_id=LA 1 [01]) -- mode Incremental
iiiiiiin
```

**Comment by WGMaker** [comment]
Hi Florian .. what WG++ version are you using for this ?

 

From: Florian Jensen ***@***.***> 
Sent: Saturday, June 8, 2024 6:46 PM
To: SilentButeo2/webgrabplus-siteinipack
***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SilentButeo2/webgrabplus-siteinipack] movistarplus.es not working
as registered_user (Issue #565)

 

movistarplus.es does not work update when logged in as a registered_user.
It works just fine when not logged in.

When logged in, it gets stuck at the following stage:

(   2/11  ) MOVISTARPLUS.ES -- chan. (xmltv_id=LA 1 [01]) -- mode
Incremental
iiiiiiin

-
Reply to this email directly, view it on GitHub
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.c
om%2FSilentButeo2%2Fwebgrabplus-siteinipack%2Fissues%2F565&data=05%7C02%7C%7
Cd42a5cb995a642278f0a08dc87e2dd2c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0
%7C638534655638837714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2
luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HOMX8R%2FTpFTrftOgkV
jQ8lxC4H2N3H3OYRf61U%2B24rY%3D&reserved=0> , or unsubscribe
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.c
om%2Fnotifications%2Funsubscribe-auth%2FACE3F4O2YQJTZIDYCJEAKF3ZGM7NTAVCNFSM
6AAAAABJAE6F5WVHI2DSMVQWIX3LMV43ASLTON2WKOZSGM2DCNZWGAYTOMI&data=05%7C02%7C%
7Cd42a5cb995a642278f0a08dc87e2dd2c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C
0%7C638534655638850511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV
2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uYz51mYNZzXQuXGXEX%
2Ff4MK8APw4Qgy5XLJyGOLRcKc%3D&reserved=0> .
You are receiving this because you are subscribed to this thread.
<https://github.com/notifications/beacon/ACE3F4PRQG3UXMWXDZKH6ALZGM7NTA5CNFS
M6AAAAABJAE6F5WWGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHIXFDMVM.gif>
Message ID: ***@***.***
***@***.***> >

**Comment by flosoft** [comment]
WebGrab+Plus V5.1.5.0

**Comment by WGMaker** [comment]
That is a known issue with 5.1.5 .. (when running as registered user, the part with the problem is not accessed but you get a lot less details) Use the evaluation build with the fix https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/evaluation-builds/WebGrabPlus_V5.1.5.2_eval_install.zip.
Or wait a few days for full version 5.2
success Jan

**Comment by flosoft** [comment]
thanks - it works with 5.2
